# Generated by Django 5.1 on 2024-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_edit', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=25)),
                ('anio_fundac', models.DateField()),
                ('fundador', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('proyectos', models.CharField(max_length=150)),
            ],
        ),
    ]
